version: '3'

services:

  node:
    image: keymetrics/pm2:8-alpine
    port: 3000:3000

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  


